version: '3.12'

#https://github.com/langchain-ai/langgraph/blob/main/docs/docs/how-tos/deploy-self-hosted.md
services:
  langgraph-redis:
    image: redis:6
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 1s
      retries: 5
  langgraph-postgres:
    image: postgres:16
    ports:
        - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
        test: pg_isready -U postgres
        start_period: 10s
        timeout: 1s
        retries: 5
        interval: 5s
  agente_api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: agente_investimento_api
    ports:
      - "3000:3000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - API_KEY_SERPER=${API_KEY_SERPER}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - REDIS_URI=redis://langgraph-redis:6379
      - DB_URI=postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
      - MODEL_ID_CHAT_IMPUT=${MODEL_ID_CHAT_IMPUT}
      - MODEL_ID_SUPERVISOR=${MODEL_ID_SUPERVISOR}
      - MODEL_ID_CHAT_RESPONSE=${MODEL_ID_CHAT_RESPONSE}
      - MODEL_ID_FUNDAMENTAL=${MODEL_ID_FUNDAMENTAL}
      - MODEL_ID_SENTIMENTO=${MODEL_ID_SENTIMENTO}
      - MODEL_ID_VALUATION=${MODEL_ID_VALUATION}
      - MODEL_ID_TECNICAL=${MODEL_ID_TECNICAL}

    volumes:
      - ./agente_investimento:/agente_investimento/agente_investimento
      - ./app:/agente_investimento/app
    depends_on:
        langgraph-redis:
            condition: service_healthy
        langgraph-postgres:
            condition: service_healthy

    restart: unless-stopped

volumes:
  langgraph-data:
    driver: local