version: '3'

tasks:
  install:
    desc: "Update pip and install dependencies"
    cmds:
      - pip install uv
      - uv pip install --upgrade pip
      - uv pip install -r requirements.txt

  format:
    desc: "Format code using Black"
    cmds:
      - black coleta_dados/*.py chat_bots/*.py tratando_dados/*.py

  format_ruff:
    desc: "Format code using Ruff"
    cmds:
      - ruff format coleta_dados/*.py chat_bots/*.py tratando_dados/*.py

  lint:
    desc: "Run linting with Pylint"
    cmds:
      - pylint --disable=R,C coleta_dados/*.py chat_bots/*.py tratando_dados/*.py

  lint_ruff:
    desc: "Run linting with Ruff"
    cmds:
      - ruff check coleta_dados/*.py chat_bots/*.py tratando_dados/*.py
  
  typepyright:
    desc: "Run type checking with Pyright"
    cmds:
      - pyright coleta_dados/*.py chat_bots/*.py tratando_dados/*.py
  
  typemypy:
    desc: "Run type checking with Mypy"
    cmds:
      - mypy coleta_dados/*.py chat_bots/*.py tratando_dados/*.py
  test:
    desc: "Run tests with pytest"
    cmds:
      - python -m pytest -vv --cov=tests/test_*.py --cov-report=xml

  refactor:
    desc: "Run formatting and linting"
    cmds:
      - task: format
      - task: lint

  all:
    desc: "Install, lint, format, test and type check"
    cmds:
      - task: install
      - task: lint
      - task: format
      - task: typepyright
